# Generated by Django 3.0.8 on 2020-07-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_id', models.CharField(default=None, max_length=50)),
                ('nick_name', models.CharField(default=None, max_length=4)),
                ('password', models.CharField(default=None, max_length=10, unique=True)),
            ],
        ),
    ]
