# Generated by Django 3.0.8 on 2020-07-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='phone_num',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='nick_name',
            field=models.CharField(default=None, max_length=4, unique=True),
        ),
    ]
