# Generated by Django 3.0.8 on 2020-07-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200703_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='new_id',
        ),
    ]
