# Generated by Django 3.0.8 on 2020-08-28 12:28

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=15)),
                ('phone_num', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=70)),
                ('store_image', models.CharField(blank=True, max_length=500, null=True)),
                ('introduce', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'bidder',
            },
        ),
        migrations.CreateModel(
            name='DetailBiddingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_and_discount', models.CharField(max_length=1000)),
                ('service_product', models.CharField(max_length=2000)),
                ('design', models.CharField(max_length=2000)),
                ('design_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=3000), size=None)),
                ('color', models.CharField(max_length=2000)),
                ('color_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=3000), size=None)),
                ('detail', models.CharField(max_length=2000)),
                ('detail_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=3000), size=None)),
                ('note', models.CharField(max_length=2000)),
                ('note_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=3000), size=None)),
            ],
            options={
                'db_table': 'detail_bid',
            },
        ),
        migrations.CreateModel(
            name='SignUpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(default='', max_length=50, unique=True, verbose_name='user_id')),
                ('nickname', models.CharField(default='', max_length=40)),
                ('phone_num', models.CharField(default=None, max_length=15)),
                ('del_or_not', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usermodel',
            },
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.CharField(max_length=20)),
                ('detail_requests', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ended_or_not', models.BooleanField(default=False)),
                ('requested_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requestmodel',
            },
        ),
        migrations.CreateModel(
            name='BiddingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=30)),
                ('certification', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to='MasterHanbok.Bidders')),
                ('detail_bidding', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterHanbok.DetailBiddingModel')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterHanbok.RequestModel')),
            ],
            options={
                'db_table': 'bid',
            },
        ),
    ]
