# Generated by Django 3.0.8 on 2020-08-28 14:43

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterHanbok', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biddingmodel',
            name='certification',
        ),
        migrations.CreateModel(
            name='CertificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('bidding_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MasterHanbok.BiddingModel')),
                ('certificated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MasterHanbok.RequestModel')),
            ],
            options={
                'db_table': 'certification',
            },
        ),
    ]
