# Generated by Django 3.0.8 on 2020-09-03 02:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterHanbok', '0002_auto_20200828_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='certification',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
    ]
