# Generated by Django 3.0.8 on 2020-07-31 08:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterHanbok', '0003_auto_20200731_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidders',
            name='store_image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='detailbiddingmodel',
            name='color_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=500), size=None),
        ),
        migrations.AlterField(
            model_name='detailbiddingmodel',
            name='design_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=500), size=None),
        ),
        migrations.AlterField(
            model_name='detailbiddingmodel',
            name='detail_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=500), size=None),
        ),
        migrations.AlterField(
            model_name='detailbiddingmodel',
            name='note_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=500), size=None),
        ),
    ]
