# Generated by Django 3.0.8 on 2020-08-28 12:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterHanbok', '0007_auto_20200804_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingmodel',
            name='certification',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='del_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
